# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('one_way_length', models.FloatField()),
                ('hours_hiking_time', models.FloatField()),
                ('trailhead', models.CharField(max_length=30)),
            ],
        ),
    ]
